apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: nextcloud
    name: mysql
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: mysql:5.7
      from:
        kind: DockerImage
        name: mysql:5.7
      importPolicy: {}
      name: "latest"
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nextcloud
    name: nextcloud
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: nextcloud:latest
      from:
        kind: DockerImage
        name: nextcloud:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nextcloud
    name: openshift-nextcloud
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/OC_PROJECT_NAME/openshift-nextcloud:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nextcloud
    name: redis
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: redis:4
      from:
        kind: DockerImage
        name: redis:4
      importPolicy: {}
      name: '4'
      referencePolicy:
        type: Source
- apiVersion: v1
  data:
    mysql-database: nextcloud
    mysql-host: mysql
    REDIS_HOST: redis
    REDIS_PORT: '6379'
    nextcloud-admin-user: admin
  kind: ConfigMap
  metadata:
    annotations: {}
    creationTimestamp: null
    name: nextcloud-config
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations: {}
    creationTimestamp: null
    name: appdata
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
    volumeName: nextcloud-appdata
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations: {}
    creationTimestamp: null
    name: var-lib-mysql
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    volumeName: nextcloud-var-lib-mysql
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations: {}
    creationTimestamp: null
    name: redis-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: nextcloud-redis-data
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations: {}
    creationTimestamp: null
    name: var-www-html
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    volumeName: nextcloud-var-www-html
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations: {}
    creationTimestamp: null
    name: builder
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations: {}
    creationTimestamp: null
    name: default
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations: {}
    creationTimestamp: null
    name: deployer
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nextcloud
    name: nextcloud
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: openshift-nextcloud:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://gitlab.com/thomassteinbach/openshift-nextcloud.git"
      contextDir: dockercontext
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: nextcloud:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: yWV_wcLbBBykaLJsVh4F
      type: GitHub
    - generic:
        secret: _fSBCmKvl7SNMUTm3Ntl
      type: Generic
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    name: mysql
  spec:
    replicas: 1
    selector:
      name: mysql
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: mysql
      spec:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-root-password
                name: nextcloud-secrets
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: mysql-database
                name: nextcloud-config
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mysql
          ports:
          - containerPort: 3306
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_ROOT_PASSWORD" mysql -h 127.0.0.1 -u root -D $MYSQL_DATABASE
                -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: var-lib-mysql
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: var-lib-mysql
          persistentVolumeClaim:
            claimName: var-lib-mysql
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql:latest
          namespace: OC_PROJECT_NAME
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nextcloud
    name: nextcloud
  spec:
    replicas: 1
    selector:
      app: nextcloud
      deploymentconfig: nextcloud
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: nextcloud
          deploymentconfig: nextcloud
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: mysql-database
                name: nextcloud-config
          - name: MYSQL_USER
            value: root
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                key: mysql-host
                name: nextcloud-config
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-root-password
                name: nextcloud-secrets
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                key: REDIS_HOST
                name: nextcloud-config
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                key: REDIS_PORT
                name: nextcloud-config
          - name: NEXTCLOUD_ADMIN_USER
            valueFrom:
              configMapKeyRef:
                key: nextcloud-admin-user
                name: nextcloud-config
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: nextcloud-admin-password
                name: nextcloud-secrets
          image: 172.30.1.1:5000/OC_PROJECT_NAME/openshift-nextcloud@sha256:983111f7d5caefc7f8e77917a8c562207858b9d1abae8e71c780d273d89eae24
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /status.php
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          name: nextcloud
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /status.php
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/www/html
            name: var-www-html
          - mountPath: /appdata
            name: appdata
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: var-www-html
          persistentVolumeClaim:
            claimName: var-www-html
        - name: appdata
          persistentVolumeClaim:
            claimName: appdata
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nextcloud
        from:
          kind: ImageStreamTag
          name: openshift-nextcloud:latest
          namespace: OC_PROJECT_NAME
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nextcloud
    name: redis
  spec:
    replicas: 1
    selector:
      app: nextcloud
      deploymentconfig: redis
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: nextcloud
          deploymentconfig: redis
      spec:
        containers:
        - image: redis@sha256:edb0f060fdeb089d2e05b7a69b0fb91418eb7d5cfb7b268b2e2f24a31807ae65
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - redis-cli -h $(hostname) ping
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - redis-cli -h $(hostname) ping
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: redis-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - redis
        from:
          kind: ImageStreamTag
          name: redis:4
          namespace: OC_PROJECT_NAME
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}
    creationTimestamp: null
    labels:
      template: mysql-persistent-template
    name: mysql
  spec:
    ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      name: mysql
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nextcloud
    name: nextcloud
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: nextcloud
      deploymentconfig: nextcloud
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nextcloud
    name: redis
  spec:
    ports:
    - name: 6379-tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: nextcloud
      deploymentconfig: redis
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: 'true'
    creationTimestamp: null
    labels:
      app: nextcloud
    name: nextcloud
  spec:
    host: OC_PROJECT_NAME.127.0.0.1.nip.io
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: nextcloud
      weight: 100
    wildcardPolicy: None
kind: List
metadata: {}
