apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: mysql-secret
objects:
- apiVersion: v1
  data:
    database-password: ${DATABASE_PASSWORD}
    database-root-password: ${DATABASE_ROOT_PASSWORD}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: mysql
  type: Opaque
parameters:
  - name: DATABASE_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    required: true
  - name: DATABASE_ROOT_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    required: true
