apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: openshift-nextcloud
    name: redis
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: redis:4
      from:
        kind: DockerImage
        name: redis:4
      generation: null
      importPolicy: {}
      name: "4"
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: openshift-nextcloud
    name: redis
  spec:
    replicas: 1
    selector:
      app: openshift-nextcloud
      deploymentconfig: redis
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: openshift-nextcloud
          deploymentconfig: redis
      spec:
        containers:
        - image: redis:4
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /data
            name: redis-data
        volumes:
        - emptyDir: {}
          name: redis-data
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - redis
        from:
          kind: ImageStreamTag
          name: redis:4
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: openshift-nextcloud
    name: redis
  spec:
    ports:
    - name: 6379-tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: openshift-nextcloud
      deploymentconfig: redis
  status:
    loadBalancer: {}
kind: List
metadata: {}
